name: fitapp
description: "OnFiNtY â€” A lightweight music player."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^17.0.0
  skeletonizer: ^2.1.0+1
  permission_handler: ^12.0.1
  on_audio_query: ^2.9.0
  audio_service: ^0.18.18
  audio_session: ^0.1.21
  just_audio: ^0.10.5
  draggable_scrollbar: ^0.1.0
  shared_preferences: ^2.5.3
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Cairo/static/Cairo-Regular.ttf
        - asset: assets/Cairo/static/Cairo-Bold.ttf
          weight: 700
    
    - family: Cagliostro
      fonts:
        - asset: assets/Cagliostro/Cagliostro-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Medium.ttf
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
    
    - family: Orbitron
      fonts:
        - asset: assets/Orbitron/static/Orbitron-Regular.ttf
    
    - family: ReemKufi
      fonts:
        - asset: assets/Reem_Kufi/static/ReemKufi-Regular.ttf
    
    - family: Tajawal
      fonts:
        - asset: assets/Tajawal/Tajawal-Regular.ttf
    
    - family: Amiri
      fonts:
        - asset: assets/Amiri/Amiri-Regular.ttf
    
    - family: Lobster
      fonts:
        - asset: assets/Lobster/Lobster-Regular.ttf
