name: fitapp
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_staggered_grid_view: 
  dio: ^5.9.0
  go_router: ^17.0.0
  skeletonizer: ^2.1.0+1
  permission_handler: ^12.0.1
  on_audio_query: ^2.9.0
  audio_service: ^0.18.18
  just_audio: ^0.10.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  build_runner: ^2.4.9
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/Cairo/static/Cairo-Regular.ttf
        - asset: assets/Cairo/static/Cairo-Bold.ttf
          weight: 700
    
    - family: Cagliostro
      fonts:
        - asset: assets/Cagliostro/Cagliostro-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: assets/Poppins/Poppins-Medium.ttf
        - asset: assets/Poppins/Poppins-Bold.ttf
          weight: 700
    
    - family: Orbitron
      fonts:
        - asset: assets/Orbitron/static/Orbitron-Regular.ttf
    
    - family: ReemKufi
      fonts:
        - asset: assets/Reem_Kufi/static/ReemKufi-Regular.ttf
    
    - family: Tajawal
      fonts:
        - asset: assets/Tajawal/Tajawal-Regular.ttf
    
    - family: Amiri
      fonts:
        - asset: assets/Amiri/Amiri-Regular.ttf
    
    - family: Lobster
      fonts:
        - asset: assets/Lobster/Lobster-Regular.ttf
